title: ofcourse
email: prevdev@gmail.com
description: "웹 개발에 꼭 필요한 정보만 모아두었어요. 간단하게 HTML, CSS 및 JavaScript를 배우세요."
baseurl: ""
url: "https://ofcourse.kr"
github_username: prev

permalink: "/:categories-course/:title"

keywords: "www,web,world wide web,html,css,javascript"
markdown: kramdown
# theme: minima
exclude: [vendor]

gems:
  - jekyll-redirect-from

future: true